baseURL = 'https://dirceu.github.io/'
languageCode = 'en-us'
title = '@dirceu'
theme = 'paper'
ignoreLogs = ['warning-goldmark-raw-html']

[menu]

  [[menu.main]]
    name = "Who?"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 2

[params]
  twitter = 'dirceu'
  github = 'dirceu'
  # instagram = 'dirceut'
  linkedin = 'dirceu'
  # mastodon = 'https://mastodon.social/@dirceut'
  # threads = '@dirceut'
  # bluesky = 'dirceu.bsky.social'
  rss = true
  avatar = 'dirceutiegs@gmail.com'
  name = 'Dirceu Pereira Tiegs'
